inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - .bundle/**
    - vendor/**/*
    - bin/**
    - db/schema.rb
    - Guardfile

Style/IfUnlessModifier:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Next:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'let']

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - db/**/*
