version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  ruby: circleci/ruby@1.4.0
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  login-to-aws:
    docker: &docker_image
      - image: 'cimg/ruby:3.1.3-node'
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME # this will use the env var
          region: $ECR_REGION # this will use the env var
      - run: &ecr_login
          name: Login to ecr
          command: |
            aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com
            aws configure export-credentials --format env
      - run: |
          cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env
  build:
    docker: &ruby_image
      - image: 'cimg/ruby:3.1.3'
    steps:
      - checkout
      - ruby/install-deps
      - slack/status: &slack_status
          fail_only: true
          only_for_branches: master
          failure_message: ":facepalm:  Failed job $CIRCLE_JOB  :homer-disappear:"
          include_job_number_field: false
  test:
    working_directory: ~/circle
    docker: *ruby_image
    steps:
      - checkout
      - setup_remote_docker: &remote_docker
          docker_layer_caching: true
      - run:
          name: test
          command: docker-compose build && docker-compose run --rm app bundle exec rspec
      - slack/status: *slack_status
  lint:
    working_directory: ~/circle
    docker: *ruby_image
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: lint
          command: bundle exec rubocop
      - slack/status: *slack_status
  security:
    working_directory: ~/circle
    docker: *ruby_image
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: security
          command: bundle exec brakeman -q --no-pager
      - slack/status: *slack_status
  build_and_push_image:
    working_directory: ~/circle/git/fb-submitter
    docker: &ecr_image
      - image: docker.io/ministryofjustice/fb-builder:latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - attach_workspace:
          at: .
      - run: &workspace_envs
          command: |
            cat bash.env >> $BASH_ENV
            echo "export BUILD_WORKER=false" >> $BASH_ENV
      - run: &base_environment_variables
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_f6b5f3b9d67ed45b0557fb62cc124dad" >> $BASH_ENV
      - run: &deploy_scripts
          name: cloning deploy scripts
          command: 'git clone --branch temporary-ecr-creds git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
          command: './deploy-scripts/bin/build'
      - slack/status: *slack_status
  build_and_push_worker_image:
    working_directory: ~/circle/git/fb-submitter
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - run: *base_environment_variables
      - run: *deploy_scripts
      - aws-cli/setup:
          role_arn: $WORKERS_ECR_ROLE_TO_ASSUME # this will use the env var
          region: $ECR_REGION # this will use the env var
      - run:
          name: Swap to workers env
          command: |
            echo "export WEB_ECR_REPOSITORY=$ECR_REPOSITORY" >> $BASH_ENV
            echo "export ECR_REPOSITORY=$WORKERS_ECR_REPOSITORY" >> $BASH_ENV
            echo "export BUILD_WORKER=true" >> $BASH_ENV
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
          command: './deploy-scripts/bin/build'
      - run:
          name: Restore env
          command: |
            echo "export ECR_REPOSITORY=$WEB_ECR_REPOSITORY" >> $BASH_ENV
            echo "export BUILD_WORKER=false" >> $BASH_ENV
      - slack/status: *slack_status
  deploy_to_test_dev:
    working_directory: ~/circle/git/fb-submitter
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - add_ssh_keys: &ssh_keys
          fingerprints:
            - "f6:b5:f3:b9:d6:7e:d4:5b:05:57:fb:62:cc:12:4d:ad"
      - run: *base_environment_variables
      - run: *deploy_scripts
      - run:
          name: deploy to test dev (EKS cluster)
          environment:
            APPLICATION_NAME: fb-submitter
            PLATFORM_ENV: test
            DEPLOYMENT_ENV: dev
            K8S_NAMESPACE: formbuilder-platform-test-dev
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status: *slack_status
  deploy_to_test_production:
    working_directory: ~/circle/git/fb-submitter
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - add_ssh_keys: *ssh_keys
      - run: *base_environment_variables
      - run: *deploy_scripts
      - run:
          name: deploy to test production (EKS cluster)
          environment:
            APPLICATION_NAME: fb-submitter
            PLATFORM_ENV: test
            DEPLOYMENT_ENV: production
            K8S_NAMESPACE: formbuilder-platform-test-production
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status: *slack_status
  deploy_to_live_dev:
    working_directory: ~/circle/git/fb-submitter
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - add_ssh_keys: *ssh_keys
      - run: *base_environment_variables
      - run: *deploy_scripts
      - run:
          name: deploy to live dev (eks)
          environment:
            APPLICATION_NAME: fb-submitter
            PLATFORM_ENV: live
            DEPLOYMENT_ENV: dev
            K8S_NAMESPACE: formbuilder-platform-live-dev
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status:
          only_for_branches: master
          success_message: ":rocket:  Successfully deployed to Live Dev  :guitar:"
          failure_message: ":alert:  Failed to deploy to Live Dev  :try_not_to_cry:"
          include_job_number_field: false
  deploy_to_live_production:
    working_directory: ~/circle/git/fb-submitter
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - add_ssh_keys: *ssh_keys
      - run: *base_environment_variables
      - run: *deploy_scripts
      - run:
          name: deploy to live production (eks)
          environment:
            APPLICATION_NAME: fb-submitter
            PLATFORM_ENV: live
            DEPLOYMENT_ENV: production
            K8S_NAMESPACE: formbuilder-platform-live-production
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status:
          only_for_branches: master
          success_message: ":rocket:  Successfully deployed to Live Production  :guitar:"
          failure_message: ":alert:  Failed to deploy to Live Production  :try_not_to_cry:"
          include_job_number_field: false
  acceptance_tests:
    docker: *ecr_image
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - run: *deploy_scripts
      - run:
          name: Run acceptance tests
          command: './deploy-scripts/bin/acceptance_tests'
      - slack/status: *slack_status
  smoke_tests:
    docker: *ecr_image
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - run: *deploy_scripts
      - run:
          name: Run smoke tests
          command: './deploy-scripts/bin/smoke_tests'
      - slack/status: *slack_status

workflows:
  version: 2
  test_and_build:
    jobs:
      - login-to-aws:
          context: &context
            - moj-forms
            - moj-forms-platform-apps
      - test:
          requires:
            -  build
      - build:
          requires:
            -  login-to-aws
      - lint:
          requires:
            -  build
      - security:
          requires:
            -  build
      - build_and_push_image:
          context: *context
          requires:
            - test
            - lint
            - security
          filters:
            branches:
              only:
                - master
      - build_and_push_worker_image:
          context: *context
          requires:
            - test
            - lint
            - security
          filters:
            branches:
              only:
                - master
      - deploy_to_test_dev:
          context: *context
          requires:
            - build_and_push_image
            - build_and_push_worker_image
      - deploy_to_test_production:
          context: *context
          requires:
            - build_and_push_image
            - build_and_push_worker_image
      - acceptance_tests:
          context: *context
          requires:
            - deploy_to_test_dev
            - deploy_to_test_production
      - deploy_to_live_dev:
          context: *context
          requires:
            - acceptance_tests
      - deploy_to_live_production:
          context: *context
          requires:
            - acceptance_tests
      - smoke_tests:
          context: *context
          requires:
            - deploy_to_live_dev
            - deploy_to_live_production
