version: 2
jobs:
  test:
    working_directory: ~/circle
    docker:
      - image: circleci/ruby:2.6.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: test
          command: docker-compose run --rm app bundle exec rspec
      - run:
          name: lint
          command: docker-compose run --rm app bundle exec rubocop
  build_and_deploy_to_test:
    working_directory: ~/circle/git/fb-submitter
    docker:
      - image: asmega/fb-builder:latest
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "5d:c8:80:1b:1a:82:af:e0:30:26:d1:62:37:7e:c9:c1"
      - run:
          name: checkout fb-submitter-deploy
          command: "GIT_SSH_COMMAND='ssh -v -i ~/.ssh/id_rsa_5dc8801b1a82afe03026d162377ec9c1 -o \"IdentitiesOnly=yes\"' git clone git@github.com:ministryofjustice/fb-submitter-deploy.git ~/circle/git/fb-submitter-deploy"
      - run:
          name: persist git crypt key to disk
          command: "echo $ENCODED_GIT_CRYPT_KEY | base64 -d > /root/circle/git_crypt.key"
      - run:
          name: unlock git crypt
          command: "cd ~/circle/git/fb-submitter-deploy && git-crypt unlock /root/circle/git_crypt.key"
      - run:
          name: npm install
          command: 'npm install'
      - run:
          name: build and push docker images
          command: './scripts/circleci_build.sh test'
      - run:
          name: deploy to test dev
          command: './scripts/circleci_deploy.sh test dev $KUBE_TOKEN_TEST_DEV'
      - run:
          name: deploy to test staging
          command: './scripts/circleci_deploy.sh test staging $KUBE_TOKEN_TEST_STAGING'
      - run:
          name: deploy to test production
          command: './scripts/circleci_deploy.sh test production $KUBE_TOKEN_TEST_PRODUCTION'
  build_and_deploy_to_integration:
    working_directory: ~/circle/git/fb-submitter
    docker:
      - image: asmega/fb-builder:latest
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "5d:c8:80:1b:1a:82:af:e0:30:26:d1:62:37:7e:c9:c1"
      - run:
          name: checkout fb-submitter-deploy
          command: "GIT_SSH_COMMAND='ssh -v -i ~/.ssh/id_rsa_5dc8801b1a82afe03026d162377ec9c1 -o \"IdentitiesOnly=yes\"' git clone git@github.com:ministryofjustice/fb-submitter-deploy.git ~/circle/git/fb-submitter-deploy"
      - run:
          name: persist git crypt key to disk
          command: "echo $ENCODED_GIT_CRYPT_KEY | base64 -d > /root/circle/git_crypt.key"
      - run:
          name: unlock git crypt
          command: "cd ~/circle/git/fb-submitter-deploy && git-crypt unlock /root/circle/git_crypt.key"
      - run:
          name: npm install
          command: 'npm install'
      - run:
          name: build and push docker images
          command: './scripts/circleci_build.sh integration'
      - run:
          name: deploy to integration dev
          command: './scripts/circleci_deploy.sh integration dev $KUBE_TOKEN_INTEGRATION_DEV'
      - run:
          name: deploy to integration staging
          command: './scripts/circleci_deploy.sh integration staging $KUBE_TOKEN_INTEGRATION_STAGING'
      - run:
          name: deploy to integration production
          command: './scripts/circleci_deploy.sh integration production $KUBE_TOKEN_INTEGRATION_PRODUCTION'
  build_and_deploy_to_live:
    working_directory: ~/circle/git/fb-submitter
    docker:
      - image: asmega/fb-builder:latest
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "5d:c8:80:1b:1a:82:af:e0:30:26:d1:62:37:7e:c9:c1"
      - run:
          name: checkout fb-submitter-deploy
          command: "GIT_SSH_COMMAND='ssh -v -i ~/.ssh/id_rsa_5dc8801b1a82afe03026d162377ec9c1 -o \"IdentitiesOnly=yes\"' git clone git@github.com:ministryofjustice/fb-submitter-deploy.git ~/circle/git/fb-submitter-deploy"
      - run:
          name: persist git crypt key to disk
          command: "echo $ENCODED_GIT_CRYPT_KEY | base64 -d > /root/circle/git_crypt.key"
      - run:
          name: unlock git crypt
          command: "cd ~/circle/git/fb-submitter-deploy && git-crypt unlock /root/circle/git_crypt.key"
      - run:
          name: npm install
          command: 'npm install'
      - run:
          name: build and push docker images
          command: './scripts/circleci_build.sh live'
      - run:
          name: deploy to live dev
          command: './scripts/circleci_deploy.sh live dev $KUBE_TOKEN_LIVE_DEV'
      - run:
          name: deploy to live staging
          command: './scripts/circleci_deploy.sh live staging $KUBE_TOKEN_LIVE_STAGING'
      - run:
          name: deploy to live production
          command: './scripts/circleci_deploy.sh live production $KUBE_TOKEN_LIVE_PRODUCTION'

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build_and_deploy_to_test:
          requires:
            - test
          filters:
            branches:
              only: master
      - confirm_integration_deploy:
          type: approval
          requires:
            - build_and_deploy_to_test
      - build_and_deploy_to_integration:
          requires:
            - confirm_integration_deploy
      - confirm_live_deploy:
          type: approval
          requires:
            - build_and_deploy_to_integration
      - build_and_deploy_to_live:
          requires:
            - confirm_live_deploy
