---
# api front-end
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "fb-submitter-api-{{ .Values.environmentName }}"
  namespace: formbuilder-platform-{{ .Values.environmentName }}
spec:
  replicas: {{ .Values.replicas.api }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.strategy.api.maxSurge }}
      maxUnavailable: {{ .Values.strategy.api.maxUnavailable }}
  selector:
    matchLabels:
      app: "fb-submitter-api-{{ .Values.environmentName }}"
  template:
    metadata:
      labels:
        app: "fb-submitter-api-{{ .Values.environmentName }}"
        appGroup: "fb-submitter"
        tier: "frontend"
    spec:
      containers:
      - name: "fb-submitter-api-{{ .Values.environmentName }}"
        image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-submitter-api:{{ .Values.circleSha1 }}"
        volumeMounts:
        - mountPath: /tmp
          name: tmp-files
        securityContext:
          runAsUser: 1001
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sleep", "10"]
        ports:
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: {{ .Values.livenessProbe.api.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.api.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.api.successThreshold }}
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3000
          initialDelaySeconds: {{ .Values.readinessProbe.api.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.api.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.api.successThreshold }}
        # non-secret env vars
        # defined in config_map.yaml
        envFrom:
          - configMapRef:
              name: fb-submitter-env-{{ .Values.environmentName }}
        env:
          - name: SENTRY_CURRENT_ENV
            value: {{ .Values.environmentName }}
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: secret_key_base
          # secrets created by terraform
          # which may or may not depend on values
          # canonically defined in secrets.tfvars
          # Some assets aren't loading properly yet
          # ...maybe an issue with how they're referenced,
          # maybe something else - re-enabled this later
          #
          # Created by cloud-platforms-environments
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rds-instance-formbuilder-submitter-2-{{ .Values.environmentName }}
                key: url
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: sentry_dsn
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: encryption_key
          - name: ENCRYPTION_SALT
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: encryption_salt
          - name: SUBMISSION_DECRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: submission_decryption_key
      volumes:
        - name: tmp-files
          emptyDir: {}
---
# workers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "fb-submitter-workers-{{ .Values.environmentName }}"
  namespace: formbuilder-platform-{{ .Values.environmentName }}
spec:
  replicas: {{ .Values.replicas.workers }}
  selector:
    matchLabels:
      app: "fb-submitter-workers-{{ .Values.environmentName }}"
  template:
    metadata:
      labels:
        app: "fb-submitter-workers-{{ .Values.environmentName }}"
        appGroup: "fb-submitter"
        tier: "workers"
    spec:
      serviceAccountName: "formbuilder-submitter-workers-{{ .Values.environmentName }}"
      containers:
      - name: "fb-submitter-workers"
        image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-submitter-workers:{{ .Values.circleSha1 }}"
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sleep", "10"]
        volumeMounts:
        - mountPath: /tmp
          name: tmp-files
        # command:
        #   - "cd /var/www/fb-submitter && bundle exec rake resque:work"
        # ports:
        #   - containerPort: 3000
        # non-secret env vars
        # defined in config_map.yaml
        envFrom:
          - configMapRef:
              name: fb-submitter-env-{{ .Values.environmentName }}
        env:
          - name: SENTRY_CURRENT_ENV
            value: {{ .Values.environmentName }}
          # third-party access keys etc, defined in secrets.yml
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: aws_access_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: aws_secret_key
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: secret_key_base
          # secrets created by terraform
          # defined in secrets.tfvars
          #
          # Created by cloud-platforms-environments
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rds-instance-formbuilder-submitter-2-{{ .Values.environmentName }}
                key: url
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: sentry_dsn
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: encryption_key
          - name: ENCRYPTION_SALT
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: encryption_salt
          - name: SUBMISSION_DECRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: submission_decryption_key
      volumes:
        - name: tmp-files
          emptyDir: {}
