apiVersion: v1
kind: Secret
metadata:
  name: fb-submitter-app-secrets-{{ .Values.environmentName }}
  namespace: formbuilder-platform-{{ .Values.environmentName }}
type: Opaque
data:
  # These credentials will be used by the submitter workers
  # to SendRawEmail via Amazon SES.
  # Therefore these must have permission to perform that operation
  # defined in their user policy.
  # TODO: script this via terraform & K8s secret
  # {{ .Values.environmentName }} values:
  aws_access_key: {{ .Values.aws_access_key }}
  aws_secret_key: {{ .Values.aws_secret_key }}
  secret_key_base: {{ .Values.secret_key_base }}
  sentry_dsn: {{ .Values.sentry_dsn }}
  encryption_key: {{ .Values.encryption_key }}
  encryption_salt: {{ .Values.encryption_salt }}
  submission_decryption_key: {{ .Values.submission_decryption_key }}
