---
# api front-end
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "fb-submitter-api-{{ .Values.environmentName }}"
  namespace: formbuilder-platform-{{ .Values.environmentName }}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "fb-submitter-api-{{ .Values.environmentName }}"
        appGroup: "fb-submitter"
        tier: "frontend"
    spec:
      containers:
      - name: "fb-submitter-api-{{ .Values.environmentName }}"
        image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-submitter-api:{{ .Values.circleSha1 }}"
        volumeMounts:
        - mountPath: /tmp
          name: tmp-files
        securityContext:
          runAsUser: 1001
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        # non-secret env vars
        # defined in config_map.yaml
        envFrom:
          - configMapRef:
              name: fb-submitter-env-{{ .Values.environmentName }}
        env:
          - name: SENTRY_CURRENT_ENV
            value: {{ .Values.environmentName }}
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: secret_key_base
          # secrets created by terraform
          # which may or may not depend on values
          # canonically defined in secrets.tfvars
          # Some assets aren't loading properly yet
          # ...maybe an issue with how they're referenced,
          # maybe something else - re-enabled this later
          #
          # Created by cloud-platforms-environments
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rds-instance-formbuilder-submitter-{{ .Values.environmentName }}
                key: url
          - name: REDIS_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: elasticache-formbuilder-submitter-{{ .Values.environmentName }}
                key: auth_token
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: elasticache-formbuilder-submitter-{{ .Values.environmentName }}
                key: primary_endpoint_address
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: sentry_dsn
      volumes:
        - name: tmp-files
          emptyDir: {}
---
# workers
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "fb-submitter-workers-{{ .Values.environmentName }}"
  namespace: formbuilder-platform-{{ .Values.environmentName }}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "fb-submitter-workers-{{ .Values.environmentName }}"
        appGroup: "fb-submitter"
        tier: "workers"
    spec:
      serviceAccountName: "formbuilder-submitter-workers-{{ .Values.environmentName }}"
      containers:
      - name: "fb-submitter-worker"
        image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-submitter-worker:{{ .Values.circleSha1 }}"
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /tmp
          name: tmp-files
        # command:
        #   - "cd /var/www/fb-submitter && bundle exec rake resque:work"
        # ports:
        #   - containerPort: 3000
        # non-secret env vars
        # defined in config_map.yaml
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "600m"
            memory: "1024Mi"
        envFrom:
          - configMapRef:
              name: fb-submitter-env-{{ .Values.environmentName }}
        env:
          - name: SENTRY_CURRENT_ENV
            value: {{ .Values.environmentName }}
          # third-party access keys etc, defined in secrets.yml
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: aws_access_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: aws_secret_key
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: secret_key_base
          # secrets created by terraform
          # defined in secrets.tfvars
          #
          # Created by cloud-platforms-environments
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rds-instance-formbuilder-submitter-{{ .Values.environmentName }}
                key: url
          - name: REDIS_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: elasticache-formbuilder-submitter-{{ .Values.environmentName }}
                key: auth_token
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: elasticache-formbuilder-submitter-{{ .Values.environmentName }}
                key: primary_endpoint_address
          - name: NOTIFY_API_KEY
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: notify_api_key
          - name: NOTIFY_EMAIL_RETURN_SETUP_EMAIL_TOKEN
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: notify_email_return_setup_email_token
          - name: NOTIFY_EMAIL_RETURN_SETUP_EMAIL_VERIFIED
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: notify_email_return_setup_email_verified
          - name: NOTIFY_EMAIL_RETURN_SETUP_MOBILE_VERIFIED
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: notify_email_return_setup_mobile_verified
          - name: NOTIFY_EMAIL_RETURN_SIGNIN_EMAIL
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: notify_email_return_signin_email
          - name: NOTIFY_EMAIL_RETURN_SIGNIN_SUCCESS
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: notify_email_return_signin_success
          - name: NOTIFY_EMAIL_GENERIC
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: notify_email_generic
          - name: NOTIFY_SMS_RETURN_SETUP_MOBILE
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: notify_sms_return_setup_mobile
          - name: NOTIFY_SMS_RETURN_SIGNIN_MOBILE
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: notify_sms_return_signin_mobile
          - name: NOTIFY_SMS_GENERIC
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: notify_sms_generic
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: fb-submitter-app-secrets-{{ .Values.environmentName }}
                key: sentry_dsn
      volumes:
        - name: tmp-files
          emptyDir: {}
