apiVersion: v1
kind: Secret
metadata:
  name: fb-submitter-app-secrets-{{ .Values.environmentName }}
  namespace: formbuilder-platform-{{ .Values.environmentName }}
type: Opaque
data:
  # These credentials will be used by the submitter workers
  # to SendRawEmail via Amazon SES.
  # Therefore these must have permission to perform that operation
  # defined in their user policy.
  # TODO: script this via terraform & K8s secret
  # {{ .Values.environmentName }} values:
  aws_access_key: {{ .Values.aws_access_key }}
  aws_secret_key: {{ .Values.aws_secret_key }}
  secret_key_base: {{ .Values.secret_key_base }}
  notify_api_key: {{ .Values.notify_api_key }}
  notify_save_return_email_template_id: {{ .Values.notify_save_return_email_template_id }}
  notify_save_return_email_magic_link_template_id: {{ .Values.notify_save_return_email_magic_link_template_id }}
  notify_save_return_email_progress_saved_template_id: {{ .Values.notify_save_return_email_progress_saved_template_id }}
  notify_email_return_setup_email_token: {{ .Values.notify_email_return_setup_email_token }}
  notify_email_return_setup_email_verified: {{ .Values.notify_email_return_setup_email_verified }}
  notify_email_return_setup_mobile_verified: {{ .Values.notify_email_return_setup_mobile_verified }}
  notify_email_return_signin_email: {{ .Values.notify_email_return_signin_email }}
  notify_email_return_signin_success: {{ .Values.notify_email_return_signin_success }}
  notify_email_generic: {{ .Values.notify_email_generic }}
  notify_sms_return_setup_mobile: {{ .Values.notify_sms_return_setup_mobile }}
  notify_sms_return_signin_mobile: {{ .Values.notify_sms_return_signin_mobile }}
  notify_sms_generic: {{ .Values.notify_sms_generic }}
  sentry_dsn: {{ .Values.sentry_dsn }}
